import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../../utils/api.js';
import { Award, Bell, Bookmark, CalendarCheck, CheckCircle2, Medal, TrendingUp } from 'lucide-react';

export const StudentProgress: React.FC = () => {
  const [progress, setProgress] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    api.get('/students/me/progress')
      .then(res => setProgress(res.data.data))
      .catch(() => setError('Could not load progress tracker.'))
      .finally(() => setLoading(false));
  }, []);

  const items = progress ? [
    ['Skills Added', progress.skillsCount, Award],
    ['Primary Skills', progress.primarySkillsCount, CheckCircle2],
    ['Certificates', progress.certificatesCount, Medal],
    ['Achievements', progress.achievementsCount, Medal],
    ['Workshops Attended', progress.workshopsAttendedCount, CalendarCheck],
    ['Upcoming Saved Workshops', progress.upcomingWorkshopsCount, CalendarCheck],
    ['Saved Schemes', progress.savedSchemesCount, Bookmark],
    ['Skill Requests', progress.skillRequestsReceivedCount, TrendingUp],
    ['Unread Notifications', progress.unreadNotificationsCount, Bell],
  ] : [];

  return (
    <div className="space-y-6 fade-in-up">
      <section className="border-b border-gray-200 pb-4">
        <h1 className="font-serif text-2xl font-bold text-maroon-700">My Progress</h1>
        <p className="text-xs text-gray-500">Calculated from your real profile, skills, participation, schemes, and notifications.</p>
      </section>
      {loading ? <div className="h-64 bg-white border rounded-xl animate-pulse" /> : error ? <p className="text-red-600">{error}</p> : progress && (
        <>
          <section className="bg-white border border-gray-150 rounded-xl p-6 shadow-sm">
            <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-5">
              <div>
                <h2 className="font-serif text-xl font-bold text-maroon-700">Profile Strength</h2>
                <p className="text-xs text-gray-500 mt-1">Completion percentage is generated by the backend progress utility.</p>
              </div>
              <div className="text-4xl font-serif font-bold text-maroon-700">{progress.profileCompletionPercentage}%</div>
            </div>
            <div className="h-3 bg-gray-100 rounded-full overflow-hidden mt-5">
              <div className="h-full bg-maroon-700" style={{ width: `${progress.profileCompletionPercentage}%` }} />
            </div>
          </section>
          <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {items.map(([label, value, Icon]: any) => (
              <div key={label} className="bg-white border border-gray-150 rounded-xl p-5 shadow-sm">
                <Icon className="w-5 h-5 text-maroon-700" />
                <div className="text-[10px] uppercase font-bold text-gray-400 mt-3">{label}</div>
                <div className="font-serif text-2xl font-bold text-maroon-700">{value}</div>
              </div>
            ))}
          </section>
          <section className="bg-rose-50 border border-rose-100 rounded-xl p-5">
            <h3 className="font-serif font-bold text-maroon-700">Recommended Next Step</h3>
            <Link to={progress.recommendedNextStep.link} className="inline-flex mt-3 px-4 py-2 bg-maroon-700 text-white rounded-md text-xs font-bold">
              {progress.recommendedNextStep.title}
            </Link>
          </section>
        </>
      )}
    </div>
  );
};
